// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RecordRemover is an autogenerated mock type for the RecordRemover type
type RecordRemover struct {
	mock.Mock
}

// DeleteRecordForCurrentUser provides a mock function with given fields: ctx, recordId
func (_m *RecordRemover) DeleteRecordForCurrentUser(ctx context.Context, recordId int64) error {
	ret := _m.Called(ctx, recordId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecordForCurrentUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, recordId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordRemover creates a new instance of RecordRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordRemover {
	mock := &RecordRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
