// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RecordCreator is an autogenerated mock type for the RecordCreator type
type RecordCreator struct {
	mock.Mock
}

// CreateRecordForCurrentUser provides a mock function with given fields: ctx, dateRecord, value
func (_m *RecordCreator) CreateRecordForCurrentUser(ctx context.Context, dateRecord time.Time, value int) error {
	ret := _m.Called(ctx, dateRecord, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecordForCurrentUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) error); ok {
		r0 = rf(ctx, dateRecord, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordCreator creates a new instance of RecordCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordCreator {
	mock := &RecordCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
