app_id: 1
app_secret: "fakesecret"
env: "local"
storage_path: "./storage/simple-diet-tracker.sqlite3"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

clients:
  grpc_auth:
    address: "localhost:40404"
    timeout: 5s
    retries_count: 5
