// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RegistrationProvider is an autogenerated mock type for the RegistrationProvider type
type RegistrationProvider struct {
	mock.Mock
}

// Registration provides a mock function with given fields: ctx, email, password
func (_m *RegistrationProvider) Registration(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Registration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegistrationProvider creates a new instance of RegistrationProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrationProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistrationProvider {
	mock := &RegistrationProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
